"""Bounded text extraction for documents imported into a student's notes."""

from __future__ import annotations

from io import BytesIO
from pathlib import PurePosixPath
from zipfile import ZipFile

MAX_DOCUMENT_BYTES = 2 * 1024 * 1024
MAX_DOCUMENT_CHARS = 50_000


class CloudDocumentError(ValueError):
    """A safe, user-facing rejection generated by document validation."""


def read_limited_response(response) -> bytes:
    """Read a streamed HTTP response without buffering unbounded file data."""
    chunks = []
    total = 0
    try:
        for chunk in response.iter_content(chunk_size=64 * 1024):
            if not chunk:
                continue
            total += len(chunk)
            if total > MAX_DOCUMENT_BYTES:
                raise CloudDocumentError("This file is larger than IntelliPlan can import (2 MB).")
            chunks.append(chunk)
    finally:
        response.close()
    return b"".join(chunks)


def extract_text(filename: str, mime_type: str, raw: bytes) -> str:
    if len(raw) > MAX_DOCUMENT_BYTES:
        raise CloudDocumentError("This file is larger than IntelliPlan can import (2 MB).")

    name = PurePosixPath(filename or "").name.lower()
    mime = (mime_type or "").lower()
    if name.endswith(".pdf") or mime == "application/pdf":
        from pypdf import PdfReader

        parts = []
        remaining = MAX_DOCUMENT_CHARS
        for page in PdfReader(BytesIO(raw)).pages:
            page_text = (page.extract_text() or "")[:remaining]
            if page_text:
                parts.append(page_text)
                remaining -= len(page_text)
            if remaining <= 0:
                break
        text = "\n\n".join(parts)
    elif name.endswith(".docx") or mime.endswith("wordprocessingml.document"):
        from docx import Document

        with ZipFile(BytesIO(raw)) as archive:
            if sum(entry.file_size for entry in archive.infolist()) > 10 * 1024 * 1024:
                raise CloudDocumentError("This Word document expands beyond IntelliPlan's 10 MB processing limit.")
        document = Document(BytesIO(raw))
        parts = []
        remaining = MAX_DOCUMENT_CHARS
        for paragraph in document.paragraphs:
            value = paragraph.text.strip()
            if value:
                parts.append(value[:remaining])
                remaining -= len(value)
            if remaining <= 0:
                break
        if remaining > 0:
            for table in document.tables:
                for row in table.rows:
                    value = " | ".join(cell.text.strip() for cell in row.cells if cell.text.strip())
                    if value:
                        parts.append(value[:remaining])
                        remaining -= len(value)
                    if remaining <= 0:
                        break
                if remaining <= 0:
                    break
        text = "\n".join(parts)
    elif mime.startswith("text/") or name.endswith((".txt", ".md", ".csv")):
        text = raw.decode("utf-8-sig", errors="replace")
    else:
        raise CloudDocumentError("IntelliPlan can import Google Docs, Sheets, Slides, PDFs, Word documents, and text files.")

    text = text.strip()
    if not text:
        raise CloudDocumentError("This file does not contain extractable text.")
    return text[:MAX_DOCUMENT_CHARS]
